name: dart_services
description: The backend service for DartPad.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  analysis_server_lib: ^0.2.5
  analyzer: ^7.4.0
  args: ^2.7.0
  bazel_worker: ^1.1.3
  dartpad_shared:
    path: ../dartpad_shared
  encrypt: ^5.0.3
  google_generative_ai: ^0.4.6
  http: ^1.3.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  path: ^1.9.0
  resp_client: ^1.2.0
  shelf: ^1.4.2
  shelf_gzip: ^4.1.0
  shelf_router: ^1.1.4
  yaml: ^3.1.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.0.0
  uuid: ^4.4.2
  sentry: ^7.7.0
  share_plus: 10.1.4
  lottie: ^3.3.1
  video_player: ^2.9.3
  chewie: ^1.10.0
  fvp: ^0.30.0
  patch_package: ^0.0.8

dev_dependencies:
  collection: ^1.19.0
  build_runner: ^2.4.11
  dart_flutter_team_lints: ^3.2.1
  grinder: ^0.9.5
  json_serializable: ^6.9.5
  package_config: ^2.2.0
  synchronized: ^3.3.1
  test: ^1.25.9
  test_descriptor: ^2.0.1
  shelf_router_generator: ^1.1.0
