# Source:
# https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/flutter/cloudbuild.yaml
#
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  # Main channel
  - name: 'docker:stable'
    args: [
      'build', '.',
      '-t', 'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter:main',
      '--build-arg', 'channel=main',
#      '--build-arg', 'COMMIT_HASH=dec2ee5',
    ]
    dir: docker/flutter-base

  # Beta channel
  - name: 'docker:stable'
    args: [
      'build', '.',
      '-t', 'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter:beta',
      '--build-arg', 'channel=beta',
    ]
    dir: docker/flutter-base

  # Stable channel
  - name: 'docker:stable'
    args: [
      'build', '.',
      '-t', 'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter:stable',
      '-t', 'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter',
      '--build-arg', 'channel=stable',
#      '--build-arg', 'COMMIT_HASH=dec2ee5',
    ]
    dir: docker/flutter-base

  # Verify image runs the `flutter` command.
  - name: 'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter'
    args: ['--help']
    dir: docker/flutter-base

options:
  machineType: 'E2_HIGHCPU_8'
images: [
  'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter:main',
  'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter:beta',
  'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter:stable',
  'asia-southeast1-docker.pkg.dev/lightning-dev-423309/development-registry-repo/flutter',
]
tags: ['cloud-builders-community']
