apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-server
  namespace: flutter-server
  labels:
    app.kubernetes.io/instance: flutter-server
    app.kubernetes.io/name: flutter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: flutter-server
      app.kubernetes.io/name: flutter-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: flutter-server
        app.kubernetes.io/name: flutter-server
    spec:
      serviceAccountName: flutter-server
      securityContext:
        runAsNonRoot: true
      containers:
        - name: flutter-server
          image: >-
            flutter-server:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: REDIS_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: flutter-server
                  key: REDIS_CONNECTION_URL
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: flutter-server
                  key: SENTRY_DSN
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: flutter-server
                  key: API_KEY
          resources:
            limits:
              cpu: 512m
              memory: 2048Mi
            requests:
              cpu: 512m
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
